const journalStyle=document.createElement('link');
journalStyle.rel='stylesheet';
journalStyle.href=new URL('../css/work-journal.css?v=20260819-1',import.meta.url).href;
document.head.appendChild(journalStyle);

const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const uid=(p='log')=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
const pad=n=>String(n).padStart(2,'0');
const today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const nowIso=()=>new Date().toISOString();
let api=null,currentUser=null,profile=null,logs=[],clients=[],unsubs=[];
let selectedId='',mode='view',manualTags=[];

function toast(message){const el=$('#toast');if(!el)return;el.textContent=message;el.classList.add('is-visible');clearTimeout(window.__worklogToast);window.__worklogToast=setTimeout(()=>el.classList.remove('is-visible'),2600)}
function owner(){return profile?.role==='owner'}
function dateLabel(key){if(!key)return'-';const [y,m,d]=String(key).split('-').map(Number);return `${y}.${pad(m)}.${pad(d)}`}
function weekStartFromInput(value){if(!/^\d{4}-W\d{2}$/.test(value))return'';const [yearText,weekText]=value.split('-W');const year=Number(yearText),week=Number(weekText);const jan4=new Date(year,0,4);const jan4Day=jan4.getDay()||7;const monday=new Date(jan4);monday.setDate(jan4.getDate()-jan4Day+1+(week-1)*7);return `${monday.getFullYear()}-${pad(monday.getMonth()+1)}-${pad(monday.getDate())}`}
function addDays(key,n){const [y,m,d]=String(key).split('-').map(Number);const date=new Date(y,m-1,d);date.setDate(date.getDate()+n);return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`}
function weekValueForDate(key=today()){const [y,m,d]=String(key).split('-').map(Number);const date=new Date(y,m-1,d);date.setHours(0,0,0,0);const thursday=new Date(date);thursday.setDate(date.getDate()+3-((date.getDay()+6)%7));const week1=new Date(thursday.getFullYear(),0,4);const week=1+Math.round(((thursday-week1)/86400000-3+((week1.getDay()+6)%7))/7);return `${thursday.getFullYear()}-W${pad(week)}`}
function periodData(type,dateValue,weekValue){if(type==='weekly'){const start=weekStartFromInput(weekValue||weekValueForDate());const end=addDays(start,6);return{periodStart:start,periodEnd:end,periodKey:weekValue||weekValueForDate(),periodLabel:`${dateLabel(start)} – ${dateLabel(end)}`,title:`${dateLabel(start)}–${pad(Number(end.slice(5,7)))}.${pad(Number(end.slice(8,10)))} 주간 업무보고서`}}const day=dateValue||today();return{periodStart:day,periodEnd:day,periodKey:day,periodLabel:dateLabel(day),title:`${dateLabel(day)} 업무보고서`}}
function plainPreview(text=''){return String(text).replace(/^#{1,6}\s+/gm,'').replace(/[*_`>-]/g,'').replace(/\s+/g,' ').trim().slice(0,150)}
function inlineMd(text){let out=esc(text);out=out.replace(/`([^`]+)`/g,'<code>$1</code>');out=out.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');return out}
function markdown(text=''){const lines=String(text).replace(/\r/g,'').split('\n');let html='',listOpen=false;const closeList=()=>{if(listOpen){html+='</ul>';listOpen=false}};for(const raw of lines){const line=raw.trimEnd();if(!line.trim()){closeList();continue}let m;if((m=line.match(/^###\s+(.+)/))){closeList();html+=`<h3>${inlineMd(m[1])}</h3>`;continue}if((m=line.match(/^##\s+(.+)/))){closeList();html+=`<h2>${inlineMd(m[1])}</h2>`;continue}if((m=line.match(/^#\s+(.+)/))){closeList();html+=`<h1>${inlineMd(m[1])}</h1>`;continue}if(/^---+$/.test(line.trim())){closeList();html+='<hr>';continue}if((m=line.match(/^\s*[-*]\s+(.+)/))){if(!listOpen){html+='<ul>';listOpen=true}html+=`<li>${inlineMd(m[1])}</li>`;continue}closeList();html+=`<p>${inlineMd(line)}</p>`}closeList();return html}
function createNav(){const nav=$('.main-nav');if(!nav||$('#worklogNavButton'))return;const btn=document.createElement('button');btn.id='worklogNavButton';btn.className='nav-link';btn.type='button';btn.dataset.route='worklog';btn.textContent='업무일지';const request=nav.querySelector('[data-route="requests"]');nav.insertBefore(btn,request||null)}
function createPage(){if($('#worklogPage'))return;const content=$('.app-content');if(!content)return;const page=document.createElement('main');page.id='worklogPage';page.className='page worklog-page';page.dataset.page='worklog';page.innerHTML=`
<section class="page-heading worklog-heading"><div><p class="eyebrow">DAILY · WEEKLY REPORT</p><h1>업무일지</h1><p>팀원이 일간·주간 업무보고서를 기록하고 프로젝트 흐름을 함께 확인합니다.</p></div><div class="worklog-heading-actions"><button id="worklogNewDaily" class="button button--primary" type="button">＋ 일간보고서</button><button id="worklogNewWeekly" class="button button--ghost" type="button">＋ 주간보고서</button></div></section>
<section class="worklog-summary"><article class="worklog-summary-card"><span>이번 달 일간보고서</span><strong id="worklogDailyCount">0</strong><small>팀 전체 기록</small></article><article class="worklog-summary-card"><span>이번 달 주간보고서</span><strong id="worklogWeeklyCount">0</strong><small>팀 전체 기록</small></article><article class="worklog-summary-card"><span>작성 팀원</span><strong id="worklogAuthorCount">0</strong><small>현재 기록 참여 인원</small></article></section>
<section class="worklog-layout"><aside class="panel worklog-panel"><div class="worklog-panel-head"><div><h2>업무보고서</h2><p>날짜·작성자·클라이언트로 찾아볼 수 있습니다.</p></div></div><div class="worklog-filter"><select id="worklogTypeFilter"><option value="all">전체 보고서</option><option value="daily">일간보고서</option><option value="weekly">주간보고서</option></select><select id="worklogAuthorFilter"><option value="all">전체 작성자</option></select><select id="worklogClientFilter" class="worklog-client-filter"><option value="all">전체 클라이언트</option></select><input id="worklogSearch" class="worklog-client-filter" type="search" placeholder="제목 · 본문 검색"></div><div id="worklogList" class="worklog-list"></div></aside><section class="panel worklog-panel"><div id="worklogEditor" class="worklog-editor"><div class="worklog-editor-empty">왼쪽에서 보고서를 선택하거나<br>새 일간·주간보고서를 작성하세요.</div></div></section></section>`;content.appendChild(page)}
function clientTagsFromText(text=''){const lower=String(text).toLocaleLowerCase();return clients.filter(c=>c.name&&lower.includes(String(c.name).toLocaleLowerCase())).map(c=>c.name)}
function unique(values){return [...new Set(values.filter(Boolean))]}
function currentTags(){return unique([...clientTagsFromText($('#worklogBody')?.value||''),...manualTags])}
function renderDetected(){const root=$('#worklogDetectedTags');if(!root)return;const tags=currentTags();root.innerHTML=tags.length?tags.map(t=>`<span class="worklog-tag">${esc(t)}</span>`).join(''):'<span style="color:#66666f;font-size:10px">본문에서 인식된 클라이언트가 없습니다.</span>'}
function titleSync(force=false){const type=$('#worklogType')?.value||'daily';const p=periodData(type,$('#worklogDate')?.value,$('#worklogWeek')?.value);const title=$('#worklogTitle');if(title&&(force||!title.dataset.userEdited||!title.value.trim()))title.value=p.title;const daily=$('#worklogDateField'),weekly=$('#worklogWeekField');if(daily)daily.hidden=type==='weekly';if(weekly)weekly.hidden=type!=='weekly'}
function editorForm(item={},type='daily'){mode='edit';selectedId=item.id||'';manualTags=[...(item.manualClientTags||[])];const reportType=item.reportType||type;const p=periodData(reportType,item.periodStart||today(),item.periodKey||weekValueForDate());const canDelete=!!item.id&&(owner()||item.authorUid===currentUser?.uid);$('#worklogEditor').innerHTML=`<form id="worklogForm" class="worklog-form"><input id="worklogId" type="hidden" value="${esc(item.id||'')}"><div class="worklog-form-top"><label class="worklog-field"><span>구분</span><select id="worklogType"><option value="daily" ${reportType==='daily'?'selected':''}>일간보고서</option><option value="weekly" ${reportType==='weekly'?'selected':''}>주간보고서</option></select></label><label id="worklogDateField" class="worklog-field"><span>날짜</span><input id="worklogDate" type="date" value="${esc(item.periodStart||today())}"></label><label id="worklogWeekField" class="worklog-field" hidden><span>주간</span><input id="worklogWeek" type="week" value="${esc(item.periodKey||weekValueForDate())}"></label></div><label class="worklog-field"><span>보고서 제목</span><input id="worklogTitle" value="${esc(item.title||p.title)}"></label><div class="worklog-detected"><div class="worklog-detected-head"><span>관련 클라이언트 · 본문에서 자동 인식</span><small>필요하면 직접 태그를 더할 수 있습니다.</small></div><div id="worklogDetectedTags" class="worklog-tags"></div><div class="worklog-manual"><input id="worklogManualTag" placeholder="클라이언트 직접 추가"><button id="worklogAddTag" type="button">태그 추가</button></div></div><label class="worklog-field"><span>업무보고서 내용</span><textarea id="worklogBody" placeholder="# 2026.08.19 업무보고서\n\nGPT가 정리해준 내용을 그대로 붙여넣으세요.">${esc(item.body||'')}</textarea></label><p class="worklog-editor-note">Markdown 제목(#, ##), 굵게(**텍스트**), 목록(-)을 그대로 사용할 수 있습니다. 저장하면 읽기 좋은 보고서 형태로 보여줍니다.</p><div class="worklog-form-actions">${canDelete?'<button id="worklogDelete" class="button button--danger" type="button">삭제</button>':''}<button id="worklogCancel" class="button button--ghost" type="button">취소</button><button class="button button--primary" type="submit">저장</button></div></form>`;titleSync(true);renderDetected();bindForm()}
function viewReport(item){mode='view';selectedId=item.id;const canEdit=owner()||item.authorUid===currentUser?.uid;$('#worklogEditor').innerHTML=`<article class="worklog-view"><header class="worklog-view-head"><div><div style="display:flex;gap:7px;align-items:center;margin-bottom:8px"><span class="worklog-type ${item.reportType==='weekly'?'is-weekly':''}">${item.reportType==='weekly'?'주간':'일간'}</span><span class="worklog-author-badge">${esc(item.authorName||'팀원')}</span></div><h2>${esc(item.title||'업무보고서')}</h2><p>${esc(item.periodLabel||dateLabel(item.periodStart))}</p><div class="worklog-tags" style="margin-top:10px">${(item.clientNames||[]).map(t=>`<span class="worklog-tag">${esc(t)}</span>`).join('')}</div></div><div class="worklog-view-actions">${canEdit?'<button id="worklogEdit" class="button button--ghost" type="button">수정</button>':''}<button id="worklogCopy" class="button button--ghost" type="button">내용 복사</button></div></header><div class="worklog-markdown">${markdown(item.body||'')}</div></article>`;$('#worklogEdit')?.addEventListener('click',()=>editorForm(item,item.reportType));$('#worklogCopy')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(item.body||'');toast('보고서 내용을 복사했습니다.')}catch{toast('내용을 복사하지 못했습니다.')}})}
function bindForm(){const body=$('#worklogBody'),title=$('#worklogTitle');body?.addEventListener('input',renderDetected);title?.addEventListener('input',()=>{title.dataset.userEdited='true'});$('#worklogType')?.addEventListener('change',()=>titleSync(true));$('#worklogDate')?.addEventListener('change',()=>titleSync(true));$('#worklogWeek')?.addEventListener('change',()=>titleSync(true));$('#worklogAddTag')?.addEventListener('click',()=>{const value=$('#worklogManualTag')?.value.trim();if(!value)return;manualTags=unique([...manualTags,value]);$('#worklogManualTag').value='';renderDetected()});$('#worklogCancel')?.addEventListener('click',()=>{const item=logs.find(x=>x.id===selectedId);item?viewReport(item):$('#worklogEditor').innerHTML='<div class="worklog-editor-empty">왼쪽에서 보고서를 선택하거나<br>새 일간·주간보고서를 작성하세요.</div>'});$('#worklogDelete')?.addEventListener('click',deleteLog);$('#worklogForm')?.addEventListener('submit',saveLog)}
async function saveLog(event){event.preventDefault();if(!api?.auth?.currentUser)return toast('로그인 상태를 확인해주세요.');const button=event.currentTarget.querySelector('button[type="submit"]');const oldText=button.textContent;button.disabled=true;button.textContent='저장 중...';try{const type=$('#worklogType').value;const p=periodData(type,$('#worklogDate')?.value,$('#worklogWeek')?.value);const body=$('#worklogBody').value.trim();if(!body)return toast('업무보고서 내용을 붙여넣어 주세요.');const id=$('#worklogId').value||uid('worklog');let old={};if($('#worklogId').value){const snap=await api.getDoc(api.doc(api.db,'workLogs',id));if(snap.exists())old=snap.data()||{}}const tags=currentTags();const clientIds=clients.filter(c=>tags.includes(c.name)).map(c=>c.id);const item={...old,id,reportType:type,periodStart:p.periodStart,periodEnd:p.periodEnd,periodKey:p.periodKey,periodLabel:p.periodLabel,title:$('#worklogTitle').value.trim()||p.title,body,clientNames:tags,clientIds,manualClientTags:manualTags,authorUid:old.authorUid||currentUser.uid,authorName:old.authorName||profile?.name||currentUser.email||'팀원',updatedAt:api.serverTimestamp(),updatedAtText:nowIso()};if(!old.createdAtText)item.createdAtText=nowIso();await api.setDoc(api.doc(api.db,'workLogs',id),item,{merge:true});selectedId=id;toast('업무보고서를 저장했습니다.')}catch(error){console.error('업무일지 저장 실패',error);toast(String(error?.code||'').includes('permission-denied')?'업무일지 저장 권한을 확인해주세요.':'업무보고서를 저장하지 못했습니다.')}finally{button.disabled=false;button.textContent=oldText}}
async function deleteLog(){const item=logs.find(x=>x.id===selectedId);if(!item||!(owner()||item.authorUid===currentUser?.uid))return;if(!confirm('이 업무보고서를 삭제할까요?'))return;try{await api.deleteDoc(api.doc(api.db,'workLogs',item.id));selectedId='';$('#worklogEditor').innerHTML='<div class="worklog-editor-empty">업무보고서를 삭제했습니다.</div>';toast('삭제했습니다.')}catch(error){console.error(error);toast('삭제하지 못했습니다.')}}
function renderSummary(){const month=today().slice(0,7);const monthLogs=logs.filter(x=>String(x.periodStart||'').startsWith(month));$('#worklogDailyCount').textContent=monthLogs.filter(x=>x.reportType!=='weekly').length;$('#worklogWeeklyCount').textContent=monthLogs.filter(x=>x.reportType==='weekly').length;$('#worklogAuthorCount').textContent=new Set(logs.map(x=>x.authorUid).filter(Boolean)).size}
function renderFilters(){const author=$('#worklogAuthorFilter'),client=$('#worklogClientFilter');if(!author||!client)return;const av=author.value||'all',cv=client.value||'all';const authors=unique(logs.map(x=>x.authorName)).sort((a,b)=>a.localeCompare(b,'ko'));author.innerHTML='<option value="all">전체 작성자</option>'+authors.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');author.value=authors.includes(av)?av:'all';const clientNames=unique(logs.flatMap(x=>x.clientNames||[])).sort((a,b)=>a.localeCompare(b,'ko'));client.innerHTML='<option value="all">전체 클라이언트</option>'+clientNames.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');client.value=clientNames.includes(cv)?cv:'all'}
function renderList(){const root=$('#worklogList');if(!root)return;const type=$('#worklogTypeFilter')?.value||'all',author=$('#worklogAuthorFilter')?.value||'all',client=$('#worklogClientFilter')?.value||'all',q=($('#worklogSearch')?.value||'').trim().toLocaleLowerCase();const list=[...logs].filter(x=>(type==='all'||x.reportType===type)&&(author==='all'||x.authorName===author)&&(client==='all'||(x.clientNames||[]).includes(client))&&(!q||`${x.title||''} ${x.body||''} ${(x.clientNames||[]).join(' ')}`.toLocaleLowerCase().includes(q))).sort((a,b)=>String(b.periodStart||'').localeCompare(String(a.periodStart||''))||String(b.updatedAtText||'').localeCompare(String(a.updatedAtText||'')));root.innerHTML=list.length?list.map(x=>`<button class="worklog-card ${x.id===selectedId?'is-active':''}" type="button" data-worklog-id="${esc(x.id)}"><span class="worklog-card-top"><strong>${esc(x.title||'업무보고서')}</strong><i class="worklog-type ${x.reportType==='weekly'?'is-weekly':''}">${x.reportType==='weekly'?'주간':'일간'}</i></span><span class="worklog-card-meta">${esc(x.authorName||'팀원')} · ${esc(x.periodLabel||dateLabel(x.periodStart))}</span><span class="worklog-card-preview">${esc(plainPreview(x.body||''))}</span><span class="worklog-tags">${(x.clientNames||[]).slice(0,5).map(t=>`<i class="worklog-tag">${esc(t)}</i>`).join('')}</span></button>`).join(''):'<p class="worklog-list-empty">저장된 업무보고서가 없습니다.</p>'}
function render(){renderSummary();renderFilters();renderList();if(mode==='view'&&selectedId){const item=logs.find(x=>x.id===selectedId);if(item)viewReport(item)}}
function bindPage(){document.addEventListener('click',e=>{const card=e.target.closest('[data-worklog-id]');if(card){selectedId=card.dataset.worklogId;mode='view';const item=logs.find(x=>x.id===selectedId);renderList();if(item)viewReport(item)}});$('#worklogNewDaily')?.addEventListener('click',()=>editorForm({},'daily'));$('#worklogNewWeekly')?.addEventListener('click',()=>editorForm({},'weekly'));['#worklogTypeFilter','#worklogAuthorFilter','#worklogClientFilter'].forEach(s=>$(s)?.addEventListener('change',renderList));$('#worklogSearch')?.addEventListener('input',renderList)}
function stop(){unsubs.forEach(f=>f?.());unsubs=[]}
async function start(user){stop();currentUser=user;if(!user){profile=null;logs=[];clients=[];render();return}try{const p=await api.getDoc(api.doc(api.db,'users',user.uid));profile=p.exists()?p.data():{name:user.email||'팀원',role:'staff'}}catch{profile={name:user.email||'팀원',role:'staff'}}unsubs.push(api.onSnapshot(api.collection(api.db,'clients'),s=>{clients=s.docs.map(d=>({id:d.id,...d.data()}));if(mode==='edit')renderDetected()}));unsubs.push(api.onSnapshot(api.collection(api.db,'workLogs'),s=>{logs=s.docs.map(d=>({id:d.id,...d.data()}));render()},error=>{console.error('업무일지 로드 실패',error);toast('업무일지를 불러오지 못했습니다. Firestore Rules를 확인해주세요.')}))}
function init(){createNav();createPage();bindPage();const wait=()=>{api=window.NineworksFirebase;if(!api)return setTimeout(wait,80);api.onAuthStateChanged(api.auth,start)};wait()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
